name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  NAME: "Snyk Demo"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: "21"

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Print name
        run: echo "Hello $NAME. $BUILD. Using Java Version $JAVA_VERSION. My API Key is ${{ secrets.API_KEY }}, GitHub Token for the action is ${{ secrets.GITHUB_TOKEN }}."
        env:
          BUILD: "We are currently running the Build Job"
      - name: Print Repo Variables
        run: echo "REPO_VAR value is ${{ vars.REPO_VAR }}"
      - name: Print Repo Environment Var
        run: echo "URL value is ${{ vars.URL }}"
          